version: "3.8"
services:
  nginx:
    image: 892444632159.dkr.ecr.us-east-1.amazonaws.com/nc-nvir-dev-test-nginx-01
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: 892444632159.dkr.ecr.us-east-1.amazonaws.com/nc-nvir-dev-test-api-01
    build:
        context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/dev.env
    ports:
      - "5000:80"
  client:
    image: 892444632159.dkr.ecr.us-east-1.amazonaws.com/nc-nvir-dev-test-client-01
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:80"
